# Generated by Django 5.0.5 on 2026-02-14 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lugar_de_recogida", models.CharField(max_length=50)),
                ("destino", models.CharField(max_length=50)),
                ("hora_inicio", models.DateTimeField(auto_now_add=True)),
                ("hora_final", models.DateTimeField(blank=True, null=True)),
                ("distancia", models.FloatField(blank=True, null=True)),
                (
                    "dinero",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "estatuto",
                    models.CharField(
                        choices=[
                            ("encourso", "Encourso"),
                            ("completado", "Completado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "conductor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.driver",
                    ),
                ),
            ],
        ),
    ]
