# Generated by Django 5.0.5 on 2026-02-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="hora_inicio",
            field=models.DateTimeField(),
        ),
    ]
