# Generated by Django 5.0.5 on 2026-02-16 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_alter_trip_hora_inicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="hora_inicio",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
