# Generated by Django 5.0.5 on 2026-02-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="No_Licencia",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
