# Generated by Django 5.0.5 on 2026-02-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_driver_no_licencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="Contraseña",
            field=models.CharField(default="1234", max_length=128),
        ),
    ]
