# Generated by Django 5.0.5 on 2026-02-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_driver_contraseña"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="Contraseña",
        ),
    ]
